const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const envFile = path.join(__dirname, 'env.js');

// Hash the admin password securely during the build phase
const rawPassword = process.env.ADMIN_PASSWORD || '';
let masterHash = '';
if (rawPassword) {
  masterHash = crypto.createHash('sha256').update(rawPassword).digest('hex');
}

// Obfuscate frontend keys to prevent simple automated scanning or direct F12 reads
const obfuscate = (str) => {
  if (!str) return '';
  return 'OBF:' + Buffer.from(str).toString('base64').split('').reverse().join('');
}

const content = `// Auto-generated by build script
window.ADMIN_PANEL_ENV = {
  SUPABASE_URL: "${obfuscate(process.env.SUPABASE_URL)}",
  SUPABASE_ANON_KEY: "${obfuscate(process.env.SUPABASE_ANON_KEY)}",
  ONESIGNAL_APP_ID: "${process.env.ONESIGNAL_APP_ID || ''}",
  ADMIN_PASSWORD_HASH: "${masterHash}",
};
`;

try {
  fs.writeFileSync(envFile, content);
  console.log('✅ Successfully generated env.js from environment variables (Password securely hashed)');
} catch (error) {
  console.error('❌ Failed to write env.js:', error);
  process.exit(1);
}
