const fs = require('fs');
const path = require('path');

const envFile = path.join(__dirname, 'env.js');

const content = `// Auto-generated by build script
window.ADMIN_PANEL_ENV = {
  SUPABASE_URL: "${process.env.SUPABASE_URL || ''}",
  SUPABASE_ANON_KEY: "${process.env.SUPABASE_ANON_KEY || ''}",
  ONESIGNAL_APP_ID: "${process.env.ONESIGNAL_APP_ID || ''}",
  ADMIN_PASSWORD: "${process.env.ADMIN_PASSWORD || ''}",
};
`;

try {
  fs.writeFileSync(envFile, content);
  console.log('✅ Successfully generated env.js from environment variables');
} catch (error) {
  console.error('❌ Failed to write env.js:', error);
  process.exit(1);
}
