[build]
  command = "npm run build"
  publish = "."

[build.environment]
  # Disable Netlify secrets scanner because Supabase Anon Key and URL are safe and required for the frontend
  SECRETS_SCAN_ENABLED = "false"
